from __future__ import annotations

from html import escape
from typing import Any

from config import HTML_OUTPUT_PATH


def _best_location(weather_rows: list[dict[str, Any]]) -> dict[str, Any]:
    """
    A simple heuristic for the summary card.
    Higher score is better: warmer, drier, less windy.
    """
    def score(row: dict[str, Any]) -> float:
        return row["temperature"] - (row["precipitation"] * 2.0) - (row["wind_speed"] * 0.15)

    return max(weather_rows, key=score)


def generate_page(weather_rows: list[dict[str, Any]], poem: str) -> None:
    """
    Write docs/index.html for GitHub Pages.
    """
    best = _best_location(weather_rows)

    rows_html = "\n".join(
        f"""
        <tr>
            <td>{escape(str(row['location']))}</td>
            <td>{escape(str(row['forecast_date']))}</td>
            <td>{row['temperature']:.1f}</td>
            <td>{row['precipitation']:.1f}</td>
            <td>{row['wind_speed']:.1f}</td>
        </tr>
        """
        for row in weather_rows
    )

    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Automated Weather Pipeline</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 0; padding: 2rem; background: #f6f8fb; color: #1f2937; }}
    .wrap {{ max-width: 960px; margin: 0 auto; }}
    .card {{ background: white; border-radius: 14px; padding: 1.25rem 1.5rem; margin-bottom: 1rem; box-shadow: 0 8px 24px rgba(0,0,0,0.08); }}
    h1, h2 {{ margin-top: 0; }}
    table {{ width: 100%; border-collapse: collapse; }}
    th, td {{ padding: 0.75rem; border-bottom: 1px solid #e5e7eb; text-align: left; }}
    th {{ background: #f3f4f6; }}
    pre {{ white-space: pre-wrap; font-family: Georgia, serif; line-height: 1.6; margin: 0; }}
    .muted {{ color: #6b7280; }}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="card">
      <h1>Tomorrow's Weather Dashboard</h1>
      <p class="muted">Automatically generated by Python, SQLite, Groq, GitHub Actions, and GitHub Pages.</p>
      <p><strong>Best place to be tomorrow:</strong> {escape(str(best['location']))}</p>
    </div>

    <div class="card">
      <h2>Forecast comparison</h2>
      <table>
        <thead>
          <tr>
            <th>Location</th>
            <th>Date</th>
            <th>Max temp (°C)</th>
            <th>Precipitation (mm)</th>
            <th>Max wind (km/h)</th>
          </tr>
        </thead>
        <tbody>
          {rows_html}
        </tbody>
      </table>
    </div>

    <div class="card">
      <h2>Bilingual poem</h2>
      <pre>{escape(poem)}</pre>
    </div>
  </div>
</body>
</html>
"""

    HTML_OUTPUT_PATH.write_text(html, encoding="utf-8")
